version: '3.4'

services:
  tododb:
    container_name: tododb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  demoservice.todoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://tododb:27017"
    depends_on:
      - tododb
    ports:
      - "8000:8080"